pipeline{
    agent any
    
    stages{
        stage('hostname'){
            steps{
                powershell 'hostname'
            }
        }
        
        stage('date'){
            steps{
                powershell 'date'
            }
        }

        stage('commit-message'){
            steps{
                echo 'webhook trigger success'
            }
        }
    }
}
